[project]
name = "SQLandPandas"
version = "0.1.0"
description = "Add a short description here"
authors = ["Woo Jin Lee <163913803+woojin-lee713@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
jupyter = ">=1.0.0,<1.1"
pandas = ">=2.2.1,<2.3"
python = ">=3.12.2,<3.13"
pytest = ">=8.1.1,<8.2"
